#Docker file para la creación de la imagen base
From debian:latest

MAINTAINER Christopher Domingo Real "christopher.domingo@s2grupo.com"

RUN apt-get update

RUN apt-get upgrade -y

RUN apt-get install -y vim

RUN apt-get install -y wget

RUN apt-get install -y curl

RUN apt-get install -y tmux
